name: weatherly
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  chopper: ^8.0.0
  loggy: ^2.0.3
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  database: ^0.4.0
  sqflite: ^2.3.3+1
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.10
  chopper_generator: ^8.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#c1f1f6"
  image: assets/images/splash_logo.png
  android: true
  ios: true
